export default (req, res) => {
  res.statusCode = 200;
  res.json({
    tier: "CHALLENGER",
    leagueId: "f3574703-bdb8-3e80-a10e-892ec93f6618",
    queue: "RANKED_TFT",
    name: "Orianna's Outriders",
    entries: [
      {
        summonerId: "AXTw-CcdPHG6ZDHjLpAWEjxelM7fxIWCY2Tc5gHEInczX6k",
        summonerName: "DarkHydra",
        leaguePoints: 1515,
        rank: "I",
        wins: 48,
        losses: 157,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "okCBv5XTDnsXDO2NVXUs2t5Q_M4kce0NGWkoQULS3Iv3tNc",
        summonerName: "niceyboii",
        leaguePoints: 911,
        rank: "I",
        wins: 103,
        losses: 527,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "jAnCmDA1FPrdYFuKwjuzJ9EL7uuA7JW3H5jQKohDDaVoU_4",
        summonerName: "FrZ CooKs",
        leaguePoints: 1000,
        rank: "I",
        wins: 88,
        losses: 648,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "xS4hxURa6MYjz3wJoA6jsGOta5RrV-KngLq8mMPsse1NGBDa",
        summonerName: "TFTACKK",
        leaguePoints: 1522,
        rank: "I",
        wins: 66,
        losses: 319,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "s1oDx8F-b_zXS46GaQA41Kph1Xxh1v3KhL7KupZvUFAVTglC",
        summonerName: "RJX ColdQQ",
        leaguePoints: 838,
        rank: "I",
        wins: 54,
        losses: 295,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "T5Phi5GV9bO8RP3WM-xFT5cjBBxVvtTtk7_-RollxxkqH3c",
        summonerName: "Kjm Jong un",
        leaguePoints: 865,
        rank: "I",
        wins: 94,
        losses: 536,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "okgpvF4B-b2qY94-1tjjIQKtH8bT-xwk2mEKXaQaNbkR2QU",
        summonerName: "Øne Łìfe",
        leaguePoints: 1016,
        rank: "I",
        wins: 103,
        losses: 580,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "o2TlEHn6bgTV_tfNALHMTUoJUOrD2dYmRzQoJLRXhHIchOo",
        summonerName: "Ahao",
        leaguePoints: 1037,
        rank: "I",
        wins: 59,
        losses: 309,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "tKR84U1QVpKgvXNgoBCqSHLz19oybgM4mraDcOtV4HVn-gM",
        summonerName: "NaPz0r",
        leaguePoints: 923,
        rank: "I",
        wins: 48,
        losses: 251,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "pKre8GdW-4HWoovI08T5uiOu7yXg1Jhh4TJL-qzyNoDR7Jk",
        summonerName: "Dalesom",
        leaguePoints: 807,
        rank: "I",
        wins: 52,
        losses: 279,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "JODnZYg5m-J9W8L6vk-z70gs9EGEZOqWzG544SuV9FJQq-Jv",
        summonerName: "Zalsher TFT",
        leaguePoints: 832,
        rank: "I",
        wins: 53,
        losses: 305,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "kdI_-Zl3togqgDRj6K2BPPYyeGa3MRxtSZmO7uInCyajVrZI",
        summonerName: "Wet Jungl3r",
        leaguePoints: 967,
        rank: "I",
        wins: 39,
        losses: 102,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "0d9zsdcH072b6pPZ4khe-1Lp4pAwkwqu8Zmdssr2UQLu0i8",
        summonerName: "Lumarpin",
        leaguePoints: 838,
        rank: "I",
        wins: 83,
        losses: 520,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "iPwkiVkZnCE5d-EJo1a5QV6SiMMi45X87x2cAcXkO_zegHk",
        summonerName: "xulei bien",
        leaguePoints: 716,
        rank: "I",
        wins: 62,
        losses: 335,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "qw4nTI_Ux30tzE8GVBDyHDKmLx8JVQf3w1heqkuXVj1X90Qx",
        summonerName: "Sayorï best girl",
        leaguePoints: 852,
        rank: "I",
        wins: 43,
        losses: 201,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "5zpGgkWeCBvdH5SNw8OBq_Fr71sQwUrzUwTRN4D9q7H8WCw",
        summonerName: "Arelianeee",
        leaguePoints: 917,
        rank: "I",
        wins: 41,
        losses: 213,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "trGAkyv_fo96dP5FpGGkm69h-RT0n6JBkPpJUIMgBhqgMM0j",
        summonerName: "PITICHI",
        leaguePoints: 1011,
        rank: "I",
        wins: 235,
        losses: 1438,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "MNp569Lq04exLled05p_qKaIOPCBybIR5PIagC_WPAJPgeA",
        summonerName: "Monsieur Tarte",
        leaguePoints: 795,
        rank: "I",
        wins: 50,
        losses: 293,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "0ITSz3KwqxOCBQnyEQDh6kAgbeQa8vIKxvlZiTpaiGZAOdOI",
        summonerName: "infernixx",
        leaguePoints: 1136,
        rank: "I",
        wins: 127,
        losses: 718,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "I7dsldxlDdRCEZ9yNunU82oM2TQM9eVHdsqALorJJaEOC8B1",
        summonerName: "Sunshee",
        leaguePoints: 683,
        rank: "I",
        wins: 44,
        losses: 258,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "nml3KQ93SHVCQLgxVkuVxlSm4_eKSlmPy_sasz9v6rBl4FU",
        summonerName: "BALOTELLI777",
        leaguePoints: 809,
        rank: "I",
        wins: 33,
        losses: 198,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "nokNrlYf3bu2XCqUN7XVM6k3dViMjwyP0pSE0J1K5Zqxisu-",
        summonerName: "FULLPOWER79",
        leaguePoints: 846,
        rank: "I",
        wins: 35,
        losses: 193,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "h1lR-vhBEGOOO2zucPQSSfVQAQLxmKvOBjG_vTHPjq8tpoE",
        summonerName: "Elkamic",
        leaguePoints: 890,
        rank: "I",
        wins: 93,
        losses: 610,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "gxtjm673yU1bekaWhgf6HH78n_wVfy7C6ybVv7tUdvY-MFs",
        summonerName: "Bimbolaloco",
        leaguePoints: 681,
        rank: "I",
        wins: 68,
        losses: 379,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "Ag1XJmsA3MZ_97CjouuecoG0YF6zyilyNt13cjVx67hJKoU",
        summonerName: "Stelfalador",
        leaguePoints: 1323,
        rank: "I",
        wins: 98,
        losses: 545,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "yB5jlKBRlBH-1IeRgByQjhzZfOrCVJGD-YT1repK9Fb2wdrT",
        summonerName: "Sologesang2",
        leaguePoints: 1489,
        rank: "I",
        wins: 77,
        losses: 289,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "_WcnaawbjkEMNqXlzRVWkxQk1PMD-loOprTqyFjGYlZQO8Gu",
        summonerName: "MasterTheoos",
        leaguePoints: 914,
        rank: "I",
        wins: 113,
        losses: 744,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "LZ6rp8duYxmvjJw0Ian1l5lG_pp7AZBrp-fWEPNIqprtVEM",
        summonerName: "Luque",
        leaguePoints: 1199,
        rank: "I",
        wins: 92,
        losses: 363,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "K98oHWjZXBru_YIsQFszn5r3gi5khHvjHKWPpuOqOmmwN_E",
        summonerName: "ßüer",
        leaguePoints: 797,
        rank: "I",
        wins: 74,
        losses: 440,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "KkZI_3iiQXmnjL-0wQfd7hZCxBzYltDWZFUTcM47hKfA2j3X",
        summonerName: "ASTROBOY10",
        leaguePoints: 1207,
        rank: "I",
        wins: 68,
        losses: 363,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "UJ5MoOE4W3XrVJ7ULgnViozYyn7Wfg27q5ecPhAv_az7BFlW",
        summonerName: "Deis1k",
        leaguePoints: 1478,
        rank: "I",
        wins: 76,
        losses: 303,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "4x4CW2Uu9msW4_64alhS9eMrOzPR0tw21s0Z6I1pg9z09y0",
        summonerName: "LONELY ODESZA",
        leaguePoints: 1360,
        rank: "I",
        wins: 84,
        losses: 476,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "BTurHGW2-HzyEHzbJGGjAyO4MqDDl1m-m6khiPDGl8YUFpOZ",
        summonerName: "TFT RoflanEbalo",
        leaguePoints: 1128,
        rank: "I",
        wins: 42,
        losses: 170,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "rVi_O1nIBWwHilr7Ko7TTMH3mtAhqhDAYmmmrDrBVicMPiE",
        summonerName: "Kevin Parker",
        leaguePoints: 927,
        rank: "I",
        wins: 130,
        losses: 699,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "qFgI3JeBUO5O5tiMAIQc0x4swthUWZ9qH9AVGkRG76smqDE",
        summonerName: "Guillosko",
        leaguePoints: 1058,
        rank: "I",
        wins: 117,
        losses: 554,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "mqjXuTq5D4XkmGWN4NMooPAqL9W8IY1xEa6r_OLqg12csgI",
        summonerName: "WiReB",
        leaguePoints: 790,
        rank: "I",
        wins: 32,
        losses: 187,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "80FzcWx-Iw-7KkSbHJ1hwGJPr4BYyfvDEfmuDf6W7cpluscty-kQKm1iBA",
        summonerName: "WIZ MaCk",
        leaguePoints: 815,
        rank: "I",
        wins: 68,
        losses: 365,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "qb70Eg0MWeNcDWYtWb_DqZ7RCCoqn6_S1vuUjdqF-F9UawM",
        summonerName: "im Aki",
        leaguePoints: 920,
        rank: "I",
        wins: 90,
        losses: 489,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "iI2NO9PqUoX0v6Vu7S4_GKMgsOTEC_NF3n4_bNq94JkLwmd5",
        summonerName: "TFTACK",
        leaguePoints: 1293,
        rank: "I",
        wins: 73,
        losses: 296,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "XNAsrcFtqtuW_3Q0vXTx9P6xpRijerCba1Ub0_e1402Jyeiv",
        summonerName: "kacpersky191TFT",
        leaguePoints: 1287,
        rank: "I",
        wins: 87,
        losses: 414,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "9vHfNd4pbrDMYC--eHMLZyBBW0G1pZHgPoQJYl-q4sZ9yhUd",
        summonerName: "AieZen",
        leaguePoints: 1056,
        rank: "I",
        wins: 34,
        losses: 241,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "Em4gZ_ztUKgNFbSoWGU9AdZOti0PZz-SJsIymcZehLm8zNY",
        summonerName: "Dedicasse Fahd",
        leaguePoints: 1318,
        rank: "I",
        wins: 35,
        losses: 129,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "a4XlxLDWV12so3Y5qTuBU8DSPF8b3qS7mSYNU9WjIPYSIaI",
        summonerName: "Lorus",
        leaguePoints: 824,
        rank: "I",
        wins: 67,
        losses: 498,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "hkFnF_RBrQqev09rgwEHks2DgeQqSU62nXW4ymi8ISuNr68",
        summonerName: "why miss",
        leaguePoints: 822,
        rank: "I",
        wins: 40,
        losses: 149,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "uW0v40RZAuxplw2s2ei6W-Y2AvtYBh0L0VlvlT2HG3dNXHs",
        summonerName: "Twiłight",
        leaguePoints: 957,
        rank: "I",
        wins: 45,
        losses: 258,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "HmsyeQ0YJyYc9JTXDcDQnTkdyLhH9idgtX1HT9L2Eql1",
        summonerName: "Defying Gravity",
        leaguePoints: 843,
        rank: "I",
        wins: 46,
        losses: 236,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "85pAtq4GE9mZAjbt_hzyT68DtqZpAXyffhBF2VzO4laznIiC",
        summonerName: "AceofMobalytics",
        leaguePoints: 1397,
        rank: "I",
        wins: 86,
        losses: 352,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "KjGHI67Hy9_i79r0CeQAfdo-7oAVXDxksqFUy9xrp7uQD1VM",
        summonerName: "TTV AL3XEM",
        leaguePoints: 935,
        rank: "I",
        wins: 140,
        losses: 820,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "Ys59umY00ncIxJVI5XeFvC0UwaBU6qBafYzPWW0t3ofk2oE",
        summonerName: "Predetorajes",
        leaguePoints: 697,
        rank: "I",
        wins: 107,
        losses: 617,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "TvWVMpaF008jPbyDoFLDkli64SkbDQW9ClQim39DPTkrFIo",
        summonerName: "uknowSawyer",
        leaguePoints: 1314,
        rank: "I",
        wins: 81,
        losses: 357,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "nVm0ck7QJK0eFu8JD9W3QsZqkcn9Vo8g6sGJ0e_2ZWSfoq7h",
        summonerName: "L2p Lelouch",
        leaguePoints: 1225,
        rank: "I",
        wins: 118,
        losses: 464,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "eqxInSVhmr3TlBAmC3G-77JlNajFLztq6h-hqpFuik0Q5BA",
        summonerName: "Løken",
        leaguePoints: 1181,
        rank: "I",
        wins: 104,
        losses: 574,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "hE_bwcmE2uniY7aMwsvCZ5H0GBBr-o-nDCd6fUlHiiBmBPQ",
        summonerName: "SwellerTiger",
        leaguePoints: 1293,
        rank: "I",
        wins: 97,
        losses: 531,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "Wh8hAhaKoMFGtmDWuObPq-VKBeKsfY0KDqfVSAu4L_LCpK4",
        summonerName: "FTW Nyxer",
        leaguePoints: 805,
        rank: "I",
        wins: 34,
        losses: 189,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "0Qp4A2Wo8mCaxKaef0q-XEHe-b8EzMkcbzYQ0O5wMesLFkFh",
        summonerName: "TTV Hamhamgang",
        leaguePoints: 1027,
        rank: "I",
        wins: 48,
        losses: 326,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "KZyegWq06KDD5HVvUIfRmV6bFdvJjAHHFYUE51-_weuIW9MO",
        summonerName: "simplywojtek tft",
        leaguePoints: 1192,
        rank: "I",
        wins: 65,
        losses: 284,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "8IZHv8xsYpmcycH9jkImUnX1-7BRTmkYs3Oz1J_g0EZXC5Y_",
        summonerName: "d wang fangirl",
        leaguePoints: 1061,
        rank: "I",
        wins: 51,
        losses: 293,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "CTValpBLIlZMUIttCdSJ2J0mdm8YMjgsyOb_CGce111NVH0",
        summonerName: "safo20",
        leaguePoints: 965,
        rank: "I",
        wins: 65,
        losses: 276,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "IRzTMpdlJVVilqJDB3xWrh10qz5mr1kN2IjMC_FG07MqU0w",
        summonerName: "FluffyHS",
        leaguePoints: 1474,
        rank: "I",
        wins: 133,
        losses: 522,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "rvHtGH1AfqwmpwCXCaQmgDMBID0elvRo_NwJTJ-k58hjdEE",
        summonerName: "YPRN Chwbk",
        leaguePoints: 867,
        rank: "I",
        wins: 45,
        losses: 197,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "BTrJzxCazb4F5_pd2DweLSBjtYlaYD750bXEn9KX1YtHbiw",
        summonerName: "Hamhamgang88",
        leaguePoints: 871,
        rank: "I",
        wins: 67,
        losses: 529,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "UPmAMYkPLPcv4Mx4u4KdVCsgb_D2mukLB15JBKH15mkX1dg",
        summonerName: "T4nPoP",
        leaguePoints: 804,
        rank: "I",
        wins: 116,
        losses: 596,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "PytXBmbv3M60FE2lreclR-efJjjD4DD2EWfERJQgHxt6jMI",
        summonerName: "DefoNotOran",
        leaguePoints: 790,
        rank: "I",
        wins: 82,
        losses: 447,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "UwHAntWXwVRM9lNn0xpuqTgP2_QAMX4bCvRvIJBUJG8aZtQ",
        summonerName: "Lallana",
        leaguePoints: 1521,
        rank: "I",
        wins: 84,
        losses: 268,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "wWT0XPiLye7iw6KcMYhsL5s5OWVkFWXTjAEZc2t4I0tALMY",
        summonerName: "iAMFrankJr",
        leaguePoints: 815,
        rank: "I",
        wins: 115,
        losses: 602,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "3H7YbClkriHbkMTZwQvhjGQRvQAS4AuBXpeq8QeMCLqxpgQ",
        summonerName: "Bränk",
        leaguePoints: 925,
        rank: "I",
        wins: 89,
        losses: 426,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "RmR0HXU6YtBk5eoM4BClDxLKq5S-S7H4Id9EppbcN6MtOF4",
        summonerName: "NES San Gofab",
        leaguePoints: 967,
        rank: "I",
        wins: 93,
        losses: 640,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "j4YJF1TbYNeOCUHaY926bkvgSnrjjCHBkVx5XQL2BU5JxyYB",
        summonerName: "cheukfly",
        leaguePoints: 1062,
        rank: "I",
        wins: 114,
        losses: 572,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "RYsd13ACq7mHYJY65AVj0bR0R1FVHSUITj5u0CXes_gPNg1g",
        summonerName: "Mamène TFT",
        leaguePoints: 694,
        rank: "I",
        wins: 111,
        losses: 637,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "4IRXrlBGf1eJufD9JyV8yZ4dlF3xubRhRwiyNPjts-zsFJPt",
        summonerName: "SAO Yuuki Asuna",
        leaguePoints: 789,
        rank: "I",
        wins: 82,
        losses: 455,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "KB9p0GqWgYEOUwm-Hd6v8yYmPQUotsX7R1koL6Xq_-PZwVE",
        summonerName: "Sologesang",
        leaguePoints: 1035,
        rank: "I",
        wins: 100,
        losses: 468,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "MJ82FT9l5yWPgW18SLK5TbRzTiDGXs8B_rv19pTj7nt6RRI",
        summonerName: "Ev4ngelion",
        leaguePoints: 839,
        rank: "I",
        wins: 72,
        losses: 473,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "Fp1W5yoyA-BJtwfFts-kw4EoiV5UfNdW8Ozq6N6g8dbgDUo",
        summonerName: "Harribo",
        leaguePoints: 883,
        rank: "I",
        wins: 61,
        losses: 425,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "EfzKulpwG5d1R6xssSKZxkFUY_Zo9nisDn_vMEkDeY_CWuI",
        summonerName: "TMS Wazzy",
        leaguePoints: 1003,
        rank: "I",
        wins: 62,
        losses: 439,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "BTV6BfpIiQp8U3Qv5bI60BbOZoWOooqPmxZW3ZS7UUHTDqQ",
        summonerName: "SUPERNANNYy",
        leaguePoints: 934,
        rank: "I",
        wins: 33,
        losses: 178,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "aOBhzgBq-nsvoQ89XBUDPxaQAObmAaDyJunlFYBvnx-Z8DTa",
        summonerName: "FB Nyu",
        leaguePoints: 1014,
        rank: "I",
        wins: 49,
        losses: 228,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "ysU4YgKfVm1N8mYreNLXt7KwsfcYztWmHlST_ByomcUrg_4",
        summonerName: "AHOY00",
        leaguePoints: 976,
        rank: "I",
        wins: 89,
        losses: 494,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "cLNo3iI8etSr6Kdw_gW1E-dRo7n1M-Pmn-lLa-aCtbCGOy90",
        summonerName: "iHG Kezman",
        leaguePoints: 1014,
        rank: "I",
        wins: 104,
        losses: 408,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "n9qNAufGwmt85sLzSNEWtBSnHReqk84V7yUuRCQztZd7RMUz",
        summonerName: "Lord Rayku",
        leaguePoints: 1568,
        rank: "I",
        wins: 60,
        losses: 304,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "LCZWYY6YrnO0EpOZdXdXel3093jDdvSX1PrnHJckLrzj0v8G",
        summonerName: "TFT Enzosexe",
        leaguePoints: 1138,
        rank: "I",
        wins: 103,
        losses: 744,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "LtSl1bFWfyg23EE-n7khVW3pIJBSaO8erT0t-C_RezGcYb0",
        summonerName: "Ray2k",
        leaguePoints: 991,
        rank: "I",
        wins: 46,
        losses: 309,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "s6KyePT2iKTKiyiBktv4EKEj_Snut9N3o5IOkp0vjdL63Ens",
        summonerName: "TTK Monchorizo",
        leaguePoints: 1018,
        rank: "I",
        wins: 93,
        losses: 419,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "Ic2Iw3KOitY5Emj5rab44NtC7-inHh2ezsiukLGiKCsSfgg",
        summonerName: "Wet Jungler",
        leaguePoints: 1565,
        rank: "I",
        wins: 60,
        losses: 274,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "pFrz3liCuBjkMB_xTXqlomJXn2Ma-fmNv0gWyLTJMk5GYbU",
        summonerName: "qwast",
        leaguePoints: 764,
        rank: "I",
        wins: 120,
        losses: 596,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "xJf2mvfpbvNiu0d6InJGVWCvESi6nX7EX0VvdjJkPDCdgns",
        summonerName: "Suidoken",
        leaguePoints: 821,
        rank: "I",
        wins: 45,
        losses: 239,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "3n9fsoXY__gcHm8cD26QM045F63sNKuNZygN1sQdRPmqIbM",
        summonerName: "Joshy Chan ",
        leaguePoints: 876,
        rank: "I",
        wins: 50,
        losses: 282,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "CAlxaFKaHHzACRhSnlVIeWfQ9bXY9lov5KzJsZxcomcJO9U",
        summonerName: "Tits",
        leaguePoints: 1157,
        rank: "I",
        wins: 76,
        losses: 341,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "gev3_U_AHrWRgopm9W8IzTU8x8J8DYvZ67_h9r8E61hkohk",
        summonerName: "PL ShinoPavels",
        leaguePoints: 899,
        rank: "I",
        wins: 82,
        losses: 431,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "joUZ_e7T1s10XTHqQnBfFmcJ9nccQoH5rF6u4xti9CE-Sio",
        summonerName: "Cute Crab",
        leaguePoints: 892,
        rank: "I",
        wins: 59,
        losses: 270,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "nD1NhqbdRL4nYbS_zloNczcLYBYiKkF-mAW5b_EBrSR5m8TU",
        summonerName: "Chepe Santacruz",
        leaguePoints: 1036,
        rank: "I",
        wins: 100,
        losses: 517,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "oFCNFSgVVRQGAH1-1ltYO1yOHZZpIEDAT7dTdI1n-EE7c5E",
        summonerName: "Diamond Penne",
        leaguePoints: 708,
        rank: "I",
        wins: 60,
        losses: 275,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "uL9ZDdbch5po9p11FhY8QuXHVwZjWClnHgVgofL0wGx52ed2",
        summonerName: "AceofSpadesITA",
        leaguePoints: 1100,
        rank: "I",
        wins: 82,
        losses: 397,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "CE2FQe4Qb2WIqL3_4WjiWgEF_p11QInY0o0ofJV4FloiqrY",
        summonerName: "I love big",
        leaguePoints: 870,
        rank: "I",
        wins: 61,
        losses: 366,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "3bKBDCan_u87UAMout9ZM-T5T5qtu8HKoFR_w8wVB-LfYXP5DG5vqw9IPg",
        summonerName: "Trop De Bol",
        leaguePoints: 1059,
        rank: "I",
        wins: 83,
        losses: 270,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "n1Hry8BZPtfFOjrm_FkMo1qCmk4Ka7ZOEjlTBrDYJXXa7Jo",
        summonerName: "Maxwellβoltzman",
        leaguePoints: 1146,
        rank: "I",
        wins: 74,
        losses: 353,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "JxcDxIcowcP7AQAgNcHudqk3xCD5zCyZQUbjcQnFgZw6XII",
        summonerName: "ØHM1E55",
        leaguePoints: 869,
        rank: "I",
        wins: 95,
        losses: 493,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "o4TmIoLUu9jrNniGtow2Lq_46h0Q2PNiKH3TbibaPuyhSEGK",
        summonerName: "KC Double61",
        leaguePoints: 1513,
        rank: "I",
        wins: 100,
        losses: 341,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "SRZPXGfq9aXNUd6I5HMuBZ4CDIFr1O2r0cuLAKfyNCP3hLE",
        summonerName: "Nyghtyx",
        leaguePoints: 1154,
        rank: "I",
        wins: 48,
        losses: 230,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "FX9dgTAiXr2MP_1S5zVc8HDZ7b9_kgmRIQZqhjT24Td-gEM",
        summonerName: "Lipo Razak",
        leaguePoints: 842,
        rank: "I",
        wins: 56,
        losses: 321,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "Fbz3LWuf1xzSp5gzTuEtdZGdwYpaBrlwMvKf35gq7mGCM32C",
        summonerName: "YxmEU",
        leaguePoints: 1002,
        rank: "I",
        wins: 40,
        losses: 148,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "KGYdfFSxU6oeGL_qYgDnCuOA4Q-NrItULKYtqnTpwGFd-Z4",
        summonerName: "IceLoom",
        leaguePoints: 953,
        rank: "I",
        wins: 57,
        losses: 286,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "QHj9ix5cJe1knrSJcynxiS5Hc0NTRHpLLDpoJKJ0XKOXJh8R",
        summonerName: "Clair666",
        leaguePoints: 971,
        rank: "I",
        wins: 127,
        losses: 658,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "RzSXukUGVM_cpjdpzwpEtomMmEwwGBZEiwNbK1-bAVGLH5vg",
        summonerName: "cybergamer69",
        leaguePoints: 918,
        rank: "I",
        wins: 34,
        losses: 72,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "_LkD5oSKxAB0NZ8G_B5rxcPlrvTXb7Vx2cuq4n0HMQvWKLI",
        summonerName: "TMS Konogan",
        leaguePoints: 778,
        rank: "I",
        wins: 71,
        losses: 427,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "ZGLcnfUxJ4SW4NkTms_i4Ved5_ZonxNC-f-H1tgbnftyKes",
        summonerName: "C0LiN",
        leaguePoints: 1130,
        rank: "I",
        wins: 68,
        losses: 542,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "ZEXmTgm8su86X3aqf8hiXfPuoAu568uqdCVjec_c6Xa4K-g",
        summonerName: "Cliinton",
        leaguePoints: 890,
        rank: "I",
        wins: 85,
        losses: 384,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: true,
      },
      {
        summonerId: "L4myGkP6pytPNpgcpTXoJlpfVNJ9fMKwsC-ljoaF-QEkCc8",
        summonerName: "I do really suck",
        leaguePoints: 1187,
        rank: "I",
        wins: 67,
        losses: 363,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "OQ6Se9HZiT-JsOVObxSj_Cgoh4bTe8sdCq0auFOhdd97DE9v",
        summonerName: "Sunshea",
        leaguePoints: 855,
        rank: "I",
        wins: 43,
        losses: 233,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "tPJ1utTraJVU0Y6Cjd3mbKuIejqFni2hKlXfbQQGUDMCKAg",
        summonerName: "re malaka re bro",
        leaguePoints: 1277,
        rank: "I",
        wins: 83,
        losses: 512,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "uWqn9sBSYbBigSMEKs9ovmo5w7t3ahWINaPaAoYm8buLhyYyXyoFNxTarQ",
        summonerName: "chikatoibimbam",
        leaguePoints: 975,
        rank: "I",
        wins: 98,
        losses: 617,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "OtzjLZJCyoybYe4c3afTkdx32bTP6VMwsItC9ThvMl8O6Us",
        summonerName: "Texita",
        leaguePoints: 1003,
        rank: "I",
        wins: 79,
        losses: 538,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "wj6kAg9SOcRvnZHtjcryR-PG6z_yn6nChBmY9vbEXHOjd14",
        summonerName: "ImSøFresh",
        leaguePoints: 1478,
        rank: "I",
        wins: 106,
        losses: 358,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "rEVVSQpgfz1wMV3YWkS_VuafAs1nJCaxG9Ejsu5JAarvCoJZ",
        summonerName: "AltNum3",
        leaguePoints: 783,
        rank: "I",
        wins: 39,
        losses: 204,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "W5DXTMB2pPUCAsoq2VEY48aHFe6J4rrnXqYjcLYmeTmpej8",
        summonerName: "Venspor",
        leaguePoints: 1139,
        rank: "I",
        wins: 71,
        losses: 391,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "vV80Ov76BSeYLuh7K-xeln9ozLRLDIJ75y3YDMSLGccAI3U",
        summonerName: "Cascendre",
        leaguePoints: 786,
        rank: "I",
        wins: 57,
        losses: 285,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "YtH2d9Ztvb8P-fE1KSDzsYP8KHALEvXKs0kYLrskT6oySU0",
        summonerName: "EML Toutoune",
        leaguePoints: 1093,
        rank: "I",
        wins: 82,
        losses: 432,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "jKUZX5A8uDekmO80a_ycPTUmuThnq84qafB7LC8lkzzQ7gs9",
        summonerName: "Nark3z",
        leaguePoints: 1037,
        rank: "I",
        wins: 99,
        losses: 516,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "rgwZ8mghUPsKOkFZZfkAs6NgXH1S19Onh4bAiAUipqN4-o9R",
        summonerName: "Ukkkkko",
        leaguePoints: 1595,
        rank: "I",
        wins: 78,
        losses: 291,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "vVDzXLj-Vmk2hICLuVGzUUJiJFoWEV8AGpctmj2mrMUF0KQ",
        summonerName: "NES Qetzer",
        leaguePoints: 908,
        rank: "I",
        wins: 53,
        losses: 226,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "GZybAFWmAXGNjkw5yiSePDmEi9vTtcpxSp0xHEqeMdfdUPut",
        summonerName: "Knusperbande",
        leaguePoints: 866,
        rank: "I",
        wins: 81,
        losses: 566,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "dqVyOsGW1Q9tL8AVuPR09-50y-Hjq_YMT35G55sWYWOHhN8",
        summonerName: "Airidux",
        leaguePoints: 984,
        rank: "I",
        wins: 104,
        losses: 615,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "KjKHC7plB252wjCVD8849OXj-aEiHQEwl68ySuUvYqegKB3R",
        summonerName: "BoLennarttyp55",
        leaguePoints: 857,
        rank: "I",
        wins: 72,
        losses: 425,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "Nc9Zkv5oEwqzXoFqpXkmz7KtMYfR_XX-zq3zIyDdRCxRV0Y",
        summonerName: "IIIQAQIII",
        leaguePoints: 838,
        rank: "I",
        wins: 56,
        losses: 261,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "i5W7-8fFVqJWy89BJEEJJ_0FTH1Nc4pdHejo1T3exD1UjMU",
        summonerName: "ImGame",
        leaguePoints: 1104,
        rank: "I",
        wins: 99,
        losses: 523,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "YdCY7yNlw3H0UUtiRdzJhImA9dXWVD21PykCRSpJTePCfdA",
        summonerName: "NES Arestidios",
        leaguePoints: 935,
        rank: "I",
        wins: 40,
        losses: 198,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "6dzCVBrJ61JjCNnP0gUoTnSHeFb9TTF8eNO7JHZSq1kilRCn",
        summonerName: "TwTvFanTheQiQi",
        leaguePoints: 1210,
        rank: "I",
        wins: 116,
        losses: 553,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "aB0sXqq7MU_yr63c_T_MxMNvzeP5B_KKyWROuHHez5lYrhpU",
        summonerName: "DIRTYMECHPLAYER",
        leaguePoints: 602,
        rank: "I",
        wins: 51,
        losses: 295,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "h7_D8DBdFkSm8msQoZMnWp8GTdIbkpOOtiLmXfIqxlpokV0",
        summonerName: "teachmeshreddín",
        leaguePoints: 932,
        rank: "I",
        wins: 76,
        losses: 298,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "KXfT2ZK8JBOfr77XIDCQbN3FB6v85DJ13q3Wroy6zKVYZwMc",
        summonerName: "Hinterado",
        leaguePoints: 911,
        rank: "I",
        wins: 43,
        losses: 236,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "6cHql0ZdKstJAj-EJX29wIuzyeLbKbAy9IFZ9hXSW_iFLek",
        summonerName: "Sunny Lu",
        leaguePoints: 931,
        rank: "I",
        wins: 44,
        losses: 251,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "gijbprk4MTt8Ig3cQFPTeB173zchB_Tw31DiQAvOKUcevqU",
        summonerName: "Tyrian Callows",
        leaguePoints: 836,
        rank: "I",
        wins: 60,
        losses: 291,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "8Vl-LNEJSgB-105JvMt4uviULgMpGHNRINRtGu7S8yURfpk",
        summonerName: "Jean Keke",
        leaguePoints: 954,
        rank: "I",
        wins: 91,
        losses: 442,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "hhJ8HsgfVp3metOmiZTDs7ERYazg9BPhbTwo7Lq9yK-heeo",
        summonerName: "Torlk",
        leaguePoints: 1022,
        rank: "I",
        wins: 118,
        losses: 723,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "jzkLCuaQC8ouV-o4-YODE6SIgu_IC6XcDHx742RQE_LKG-E",
        summonerName: "Sonìdou",
        leaguePoints: 807,
        rank: "I",
        wins: 159,
        losses: 898,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "QkuSow8roqpDWzgpNzJOc-ndRQoOg7dt-KV1cJ8CqsRYYcI",
        summonerName: "TNG Lucy Chan",
        leaguePoints: 1386,
        rank: "I",
        wins: 74,
        losses: 463,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "gGU1uTqYauEWQ015tWRAaWbb1Vt_Xvnc6EnWO5aXuDkUPVDked2ii4Eqkw",
        summonerName: "WORLD CHAMP DIFF",
        leaguePoints: 1094,
        rank: "I",
        wins: 55,
        losses: 174,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "UVnc9R1XbTJFTS6chUp8wFAvNVpkwhTeIZG0cvv7TOkq",
        summonerName: "Loescher",
        leaguePoints: 912,
        rank: "I",
        wins: 65,
        losses: 397,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "2ErMZYmAo9OLLTv3DLjVq_E5dVcuCBIc3HpEYm7eLJVcW18",
        summonerName: "gluteus maxímus",
        leaguePoints: 1618,
        rank: "I",
        wins: 94,
        losses: 375,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "qeFiddP7es47kJwZzCcbwuHh8NQlBw9JEjfdTTFA4WDTK9FX",
        summonerName: "iamTLT",
        leaguePoints: 961,
        rank: "I",
        wins: 55,
        losses: 310,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "BFPa3v4lyZHJZCsJIU4LnAAYryw51f3C28P7TOI0gPZN8og",
        summonerName: "PcIsMyOnlyGirl",
        leaguePoints: 945,
        rank: "I",
        wins: 59,
        losses: 227,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "1X8FPYYPCN-eaqTcQCHvi24r-_eaGkOeBNueg2HqcbruAwY",
        summonerName: "josh10",
        leaguePoints: 1012,
        rank: "I",
        wins: 73,
        losses: 514,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "MgehLbtBzlBiMxLvzbaVzgDAbf6F7xwiJuVVU_dgoafMaQE",
        summonerName: "pBLhawk",
        leaguePoints: 815,
        rank: "I",
        wins: 59,
        losses: 278,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "MmhBMHT-7MYHLQhXr_zxDJje4GW3JRHBvVLe9zzdA7oWbyI",
        summonerName: "B Ø G S U",
        leaguePoints: 829,
        rank: "I",
        wins: 65,
        losses: 269,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "VJ67QUi9q1iQIAaI_2lg9gP7U-z_quBolmIzq0FEYyYRQd8",
        summonerName: "KTM Balu",
        leaguePoints: 839,
        rank: "I",
        wins: 87,
        losses: 534,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "2cxJxf_fpRAt6X7f3BJ0e4hoXjN4ANttc4rFogetPQK0k1aB",
        summonerName: "TKey Reformed",
        leaguePoints: 774,
        rank: "I",
        wins: 51,
        losses: 303,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "YV3YHjeiIVTURqTeSVA5ysACAkTamx-9XR9bqi-5CKM1o5nH",
        summonerName: "Ukkkko",
        leaguePoints: 1556,
        rank: "I",
        wins: 96,
        losses: 299,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "kgUUWk0cFJNbLdtUDP0TL5VOAOWDJ8-OKeRjv-cG6ypkUeVr",
        summonerName: "Les collègues",
        leaguePoints: 1540,
        rank: "I",
        wins: 63,
        losses: 236,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "9TXS5m-QMHZ-VglT0VJ_lrpmvhqJjfTX--Bv6ao71X9_geq6",
        summonerName: "JollyFaker777",
        leaguePoints: 872,
        rank: "I",
        wins: 49,
        losses: 351,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "ytnmCQlzY1_nIdyesypFrH1xzOAlBvPJKOi69MvUSdJ0LSVd",
        summonerName: "TFT OMEGALULLLL",
        leaguePoints: 823,
        rank: "I",
        wins: 83,
        losses: 575,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "Nww_p5YHOkT00AR9NbaIutD3v48VH9ETQNgawV7TEoa74mk",
        summonerName: "ZL98",
        leaguePoints: 802,
        rank: "I",
        wins: 38,
        losses: 168,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "JxPzFTujwHAvUMxzGAIZm1D3HDUlZQAO9ArgFArEcKdo71M",
        summonerName: "MasterMamba",
        leaguePoints: 843,
        rank: "I",
        wins: 48,
        losses: 442,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "VeidBQg_LGg75LlhoL1HkFrIIBwqPKvPhaSrpPBAnXOek7DZ",
        summonerName: "zoomgowy",
        leaguePoints: 994,
        rank: "I",
        wins: 41,
        losses: 193,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "b4zshlPTe5YnU16EkhBSE1Fnh0gesJRtrlh6Yta856fajpw",
        summonerName: "Lonnen ",
        leaguePoints: 1334,
        rank: "I",
        wins: 87,
        losses: 524,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "yMfV-5_L-3PC8V1aszn1ktjJ7HPR1BGw9abOs_6KYAedbzab",
        summonerName: "HeinoDoe",
        leaguePoints: 875,
        rank: "I",
        wins: 60,
        losses: 376,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "glQHP9GZM5J_xGNcrwMriQcd0XURO7AHM_Qxwm7CmJDkMpM",
        summonerName: "Oberes",
        leaguePoints: 1101,
        rank: "I",
        wins: 63,
        losses: 344,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "URk7p0Gp6tFoHQSKyw5XtjMgk__g_cnr0RK3hZW7c0qDtv4",
        summonerName: "BKrisz",
        leaguePoints: 928,
        rank: "I",
        wins: 48,
        losses: 232,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "2JzmrWCzC0y-2iPmX577-To6tKGOWqsykZ3aqQFrlhbK_BJ1",
        summonerName: "GingGG",
        leaguePoints: 1085,
        rank: "I",
        wins: 76,
        losses: 299,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "gu6t1M0rWF7yBfPZV4Q1R9F6RHR-c1yNwHtb0d99yAtu-JE",
        summonerName: "ChanseyNES",
        leaguePoints: 718,
        rank: "I",
        wins: 55,
        losses: 323,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "yE1JlgkmA5NfQ6dMXGA0mXWJBanBH5I_rtdAZFBa5z0iARDl",
        summonerName: "MrCastrec",
        leaguePoints: 955,
        rank: "I",
        wins: 46,
        losses: 260,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "Yppur3CiGaJgZa6KqyxrBgckq-D1M978MITUxzGAlFEdDqE",
        summonerName: "la chinoise miam",
        leaguePoints: 805,
        rank: "I",
        wins: 37,
        losses: 155,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "XWOlqI24_WWE-_FLW80UaNVSI91lP1L_eiL5aQbHpySo3GY",
        summonerName: "Un11d",
        leaguePoints: 1050,
        rank: "I",
        wins: 38,
        losses: 182,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "uWEpLc77DkEQzM1jtfu_yx_hNNsPZ45qrteBT0RMhahiK3Y",
        summonerName: "Smoooth Brain",
        leaguePoints: 839,
        rank: "I",
        wins: 56,
        losses: 334,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "xFVCDppsxiJu17kn1PBdEhf40wtsd6iZ_ciGGCO9XRUw6gI",
        summonerName: "Can I trust you",
        leaguePoints: 809,
        rank: "I",
        wins: 38,
        losses: 156,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "pVgk_GrVQwPCBooYMX1uU_Zc27kgDW-xpGY_ktipSPkQNfA",
        summonerName: "bellae",
        leaguePoints: 1284,
        rank: "I",
        wins: 47,
        losses: 334,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "u6Lc_R9Z-id3YjKNjsAp2H9gsR7fs0wJoZsGFCII6T0mGdQ",
        summonerName: "buifr",
        leaguePoints: 823,
        rank: "I",
        wins: 54,
        losses: 319,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "fJZFNK9ZiyoVkagHnHPohPaX9yevJiP0O1wAWF0szaSGusQ",
        summonerName: "Kéjà",
        leaguePoints: 1163,
        rank: "I",
        wins: 75,
        losses: 443,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "xnOtE2AfNmrmrl7ssLQyn5sEQ790XRHzWJHKXbX-P-jLUFw",
        summonerName: "MHStana",
        leaguePoints: 847,
        rank: "I",
        wins: 177,
        losses: 1047,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "fZC5l3ryuNhgD0y2cTPfNH0WWknlO7_fnABCsycE9DRH0hU",
        summonerName: "SLY Voltariux",
        leaguePoints: 1378,
        rank: "I",
        wins: 120,
        losses: 439,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "7CviGlSJura8y3K7r8RmMtkI39rC_6tHZBsgPJeeEsgGLxc",
        summonerName: "Lyyyress",
        leaguePoints: 937,
        rank: "I",
        wins: 49,
        losses: 262,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "XWkA0Cd8rxIg5lQe87Xx4DO5xvsYgkyF8dqRjbTOwkOaWwNu",
        summonerName: "ThePikachuTFT",
        leaguePoints: 820,
        rank: "I",
        wins: 63,
        losses: 422,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "1gm48NvjCjYjtBvcmWb4DkYZ7JOp7K01l8XGYh7SGuVZXXs",
        summonerName: "Babyguana TTV",
        leaguePoints: 732,
        rank: "I",
        wins: 70,
        losses: 524,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "qXtgeK-5FEnovj8uYMOBgrXrSNNxnswcReiaWIuvYPv2HvI",
        summonerName: "Un33d",
        leaguePoints: 1387,
        rank: "I",
        wins: 70,
        losses: 332,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "VOXW7WLE3_VRU5OOtPwqdP5I09P7s3cN85LkZCr-2X-P-ps",
        summonerName: "ArmaTruc",
        leaguePoints: 815,
        rank: "I",
        wins: 34,
        losses: 217,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "saBRYUf2fxi2B-L-3_vHheKDZlZhPN2lkfbvLzTg_8gcEwI",
        summonerName: "SharpeyX",
        leaguePoints: 1123,
        rank: "I",
        wins: 91,
        losses: 523,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "nqRpotgiBzpgJTXamgRTh87mMeWsHjC_uWb0lJy5YVWCEnNT",
        summonerName: "TarteMan",
        leaguePoints: 768,
        rank: "I",
        wins: 39,
        losses: 183,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "XvF45WRaIyUInfcG6MYzPy4plpNMmcNsy9KTJGfM2qcS62YI",
        summonerName: "Seji",
        leaguePoints: 1058,
        rank: "I",
        wins: 63,
        losses: 340,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "DpejTwEcJrw0LllOWu4gBg-70jVfCa2RkK9iWmBOD-k16Jw",
        summonerName: "twtv xus0o",
        leaguePoints: 807,
        rank: "I",
        wins: 81,
        losses: 378,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "GI2xiHaAu96d84MyQ1cw50xjEAYCY0aKmRL0I89B2Gx8sRA",
        summonerName: "ZeròX",
        leaguePoints: 909,
        rank: "I",
        wins: 72,
        losses: 384,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "iqctJWHrZoPpzh7UH5S36kivAnBz7ZAZro0xNHQwUtRewto",
        summonerName: "DAKT4R",
        leaguePoints: 1058,
        rank: "I",
        wins: 44,
        losses: 295,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "WDUK_VfOcFguuqhDY0fvQYhnkcra2hXrZlcJPrzjlOd516eg",
        summonerName: "idlemonk TFT",
        leaguePoints: 836,
        rank: "I",
        wins: 65,
        losses: 363,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "-wAsojtO5_48kbBEnUZMggwKUJM24I6T-YcjsW86HQCx60I",
        summonerName: "R E H N Z",
        leaguePoints: 850,
        rank: "I",
        wins: 40,
        losses: 195,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "RFNRfxkV41bwv1BpPfgwzbKDa4ffpre5EPFfcsAyrPD9ZRc",
        summonerName: "Salvyyy",
        leaguePoints: 1681,
        rank: "I",
        wins: 67,
        losses: 223,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "HyHvZOz7qnBJMCqx98pcolNJWj57RWru0BmM_eKDnHvkUTYp",
        summonerName: "Fabulotus",
        leaguePoints: 1078,
        rank: "I",
        wins: 72,
        losses: 441,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "B3zLCKqHVifhQl6_BCZO8N5K6rZPv9pTDtbEze4EzUFsWq0",
        summonerName: "FBX Jesus",
        leaguePoints: 818,
        rank: "I",
        wins: 84,
        losses: 540,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "cyB08aGY4cdVF5gIGO-4efXmQQ6eQT0Ivgb9uy0iT2RXQ6Zl",
        summonerName: "Idlemonkkk",
        leaguePoints: 1011,
        rank: "I",
        wins: 48,
        losses: 267,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "0psX2t26mAvu5NBFqGnnkNG92RVj0EKJAO2SJpl4VzREPia7",
        summonerName: "MTFM ShinoPavels",
        leaguePoints: 821,
        rank: "I",
        wins: 49,
        losses: 223,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "14MQfkd3i-7ozeKtbxtICL9GWVx-oyk7R9sEYDaNsjmJxrc",
        summonerName: "San Jomian",
        leaguePoints: 931,
        rank: "I",
        wins: 77,
        losses: 561,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "jHF2Gq7jfL-U1s4VhLRZ6EAcLOZpRixA11GY1R8EWWRMY88",
        summonerName: "FlacoTheChapo",
        leaguePoints: 1037,
        rank: "I",
        wins: 55,
        losses: 290,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "N1LkHvxf-2dAwX7rMtr3XQSQgSgahKJs7oftP9RWpcBr2zw",
        summonerName: "Kamidakara",
        leaguePoints: 800,
        rank: "I",
        wins: 53,
        losses: 334,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "UiatJpqfDCWhyZH8a1rdLPs8X4sAaBiU93RTxBcRX3Higlhc",
        summonerName: "TFT shircane",
        leaguePoints: 1085,
        rank: "I",
        wins: 152,
        losses: 865,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "Ijh4XxWqow0ROEsCa708kQkP6MmB3_SNI3IphAbbYOFipVA",
        summonerName: "zoro5773",
        leaguePoints: 1009,
        rank: "I",
        wins: 110,
        losses: 684,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "BonD7ZAHKf8TdSdzwK0S1XiZaR_Gk2s8fG_doLLL2WiKff4",
        summonerName: "Subtlecloud",
        leaguePoints: 1042,
        rank: "I",
        wins: 88,
        losses: 464,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "N4s5ZWoKyF_GqqdFWH3ontIpF-cZpJRh2UiOTk5vgo15hVc",
        summonerName: "Von Mackensen",
        leaguePoints: 842,
        rank: "I",
        wins: 45,
        losses: 236,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "0ELy84FaWcs01a0m8m-8KTGm1pCzS32efujvRofXt3Yfx_c",
        summonerName: "VGIA Snoodyboo",
        leaguePoints: 918,
        rank: "I",
        wins: 128,
        losses: 585,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "3vYUvh_ocZ02LwJLWGsCv9adkN6_nqhnFyLzaF1qxl1h_7SE",
        summonerName: "Sebadam TFT",
        leaguePoints: 998,
        rank: "I",
        wins: 35,
        losses: 176,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "6bFGTN5NTXuyH4Im-LJfjm94187IQK19JST2zm6po2K5SQUL",
        summonerName: "LilΤado",
        leaguePoints: 909,
        rank: "I",
        wins: 117,
        losses: 766,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "5Cym4UuPw-mgmFHFAxKYdhe8le_dlp5c7dt3g_L_ek67nCmF",
        summonerName: "KR HyunTer",
        leaguePoints: 1723,
        rank: "I",
        wins: 71,
        losses: 216,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "NEvCfdjs8YvTBvMJVZLBXBp-jAgyIOVWE2Q2XzGVvoynZhr2",
        summonerName: "KéjaTFT",
        leaguePoints: 1071,
        rank: "I",
        wins: 58,
        losses: 198,
        veteran: false,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
      {
        summonerId: "7Vlg3KcioY0jKZciJmeCHwHm3iTKhIfcreNOPHxrOCmuFF4U",
        summonerName: "kanjugenn",
        leaguePoints: 809,
        rank: "I",
        wins: 118,
        losses: 611,
        veteran: false,
        inactive: false,
        freshBlood: true,
        hotStreak: false,
      },
      {
        summonerId: "BcgK-J7lcTsliyB4-uCQKvkTi_Lh3LUYAryvSCMOJdyEdeY",
        summonerName: "AKA magic",
        leaguePoints: 1327,
        rank: "I",
        wins: 71,
        losses: 347,
        veteran: true,
        inactive: false,
        freshBlood: false,
        hotStreak: false,
      },
    ],
  });
};
